services:
  django:
    build: . #sabe que tem que pegar do Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app

  postgres:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data #volume serve para backup dos dados
    environment:
      - POSTGRES_DB=django
      - POSTGRES_PASSWORD=root
