services:
  django:
    #build: .
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - .:/app

  postgres:
    image: postgres:15.8-alpine3.20
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_PASSWORD=robs

  pgadmin:
    image: dpage/pgadmin4:8.11.0
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=robs
    depends_on:
      - postgres
